### PR TITLE
Use single lodash dependency.

### PR DESCRIPTION
**Pull request by arendjr**
Using Node.js v6.9.1, when I ran `npm install` on your project, I got the following output:

    $ npm install
    npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
    npm WARN prefer global coffee-script@1.10.0 should be installed with -g
    
    > graphql-anywhere@1.0.0 prepublish /home/arendjr/Projects/graphql-anywhere
    > npm run compile
    
    
    > graphql-anywhere@1.0.0 compile /home/arendjr/Projects/graphql-anywhere
    > tsc
    
    typings.d.ts(10,17): error TS2694: Namespace '_' has no exported member 'isObject'.
    typings.d.ts(15,17): error TS2694: Namespace '_' has no exported member 'isEqual'.
    typings.d.ts(20,17): error TS2694: Namespace '_' has no exported member 'isNull'.
    typings.d.ts(25,17): error TS2694: Namespace '_' has no exported member 'isString'.
    typings.d.ts(30,17): error TS2694: Namespace '_' has no exported member 'has'.
    typings.d.ts(35,17): error TS2694: Namespace '_' has no exported member 'assign'.
    typings.d.ts(40,17): error TS2694: Namespace '_' has no exported member 'merge'.
    typings.d.ts(45,17): error TS2694: Namespace '_' has no exported member 'includes'.
    typings.d.ts(50,17): error TS2694: Namespace '_' has no exported member 'isNumber'.
    typings.d.ts(55,17): error TS2694: Namespace '_' has no exported member 'isBoolean'.
    typings.d.ts(60,17): error TS2694: Namespace '_' has no exported member 'isUndefined'.
    typings.d.ts(65,17): error TS2694: Namespace '_' has no exported member 'forOwn'.
    typings.d.ts(70,17): error TS2694: Namespace '_' has no exported member 'omit'.
    typings.d.ts(75,17): error TS2694: Namespace '_' has no exported member 'mapValues'.
    typings.d.ts(80,17): error TS2694: Namespace '_' has no exported member 'cloneDeep'.
    typings.d.ts(85,17): error TS2694: Namespace '_' has no exported member 'countBy'.
    typings.d.ts(90,17): error TS2694: Namespace '_' has no exported member 'identity'.
    typings.d.ts(95,17): error TS2694: Namespace '_' has no exported member 'flatten'.
    typings.d.ts(100,17): error TS2694: Namespace '_' has no exported member 'pick'.

    npm ERR! Linux 4.4.0-53-generic
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "compile"
    npm ERR! node v6.9.1
    npm ERR! npm  v3.10.8
    npm ERR! code ELIFECYCLE
    npm ERR! graphql-anywhere@1.0.0 compile: `tsc`
    npm ERR! Exit status 2
    npm ERR! 
    npm ERR! Failed at the graphql-anywhere@1.0.0 compile script 'tsc'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the graphql-anywhere package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     tsc
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs graphql-anywhere
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls graphql-anywhere
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/arendjr/Projects/graphql-anywhere/npm-debug.log
    
    npm ERR! Linux 4.4.0-53-generic
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
    npm ERR! node v6.9.1
    npm ERR! npm  v3.10.8
    npm ERR! code ELIFECYCLE
    npm ERR! graphql-anywhere@1.0.0 prepublish: `npm run compile`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the graphql-anywhere@1.0.0 prepublish script 'npm run compile'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the graphql-anywhere package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     npm run compile
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs graphql-anywhere
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls graphql-anywhere
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/arendjr/Projects/graphql-anywhere/npm-debug.log

This PR solves the issue by using a single lodash dependency, rather than using individual modules per function. I believe this to be a good idea anyway based on the [cost of small modules](https://nolanlawson.com/2016/08/15/the-cost-of-small-modules/).

I realize there may be a downside for users that are not using either automatic tree-shaking or custom lodash bundles, but it is my belief that users that do care about download size should at least use one of those solutions. I hope you agree :)

### CODE REVIEW

**Comment by arendjr** [comment]
Agreement should be signed now.

**Comment by helfer** [comment]
@arendjr I think the problem with this is that it will blow up the bundle size of this package, which we really want to avoid. We can use a single import, but then everything should be imported like this: `import assign from 'lodash/assign'` etc.

@stubailo I think we should add a filesize limit to this package as well, if we haven't already.

**Comment by arendjr** [comment]
What do you mean exactly by "the bundle size of this package"? I ask because I see no bundled distributables of this package. So am I correct to assume you mean any project dependending on this package will then by proxy depend on the whole of lodash, which will inflate their bundle sizes? Because that depends on how that particular project is set up. In my case I include a custom built copy of lodash (thanks to lodash' extensive build system), so for me it's the other way around: using separate packages actually yields me bigger bundles than just referring to "lodash" which includes all the methods I want to bundle already. I think other projects may also benefit in bundle size from simply using a single "lodash" package, namely those that are set up to do proper tree-shaking. I'll admit it may inflate the bundle for people that are using neither solution, but then I'd say you ought to use one of those if you really care about bundle size (it'll actually get you the smallest bundles).

Anyway, if you don't want to merge this PR, I would still favor the `lodash/assign`-style import over `lodash.assign`. It'll still result in fewer packages needing to be installed and would reduce the amount I need to deviate in my fork to get optimal bundle sizes for my own project.

**Comment by stubailo** [comment]
Yeah I'm interested in switching to `lodash/X` imports. Even more interested in removing the lodash dep entirely.

**Comment by stubailo** [comment]
So, good news guys - I removed literally all of the dependencies. Hope I didn't break anything! The only thing is that I had to reimplement `merge`.

**Comment by arendjr** [comment]
Cool! :)

**Comment by stubailo** [comment]
However somehow republishing the package resulted in many typescript errors. So.... let's see what happened!

**Pull request merged**
