### PR TITLE
[WIP] Promises support in resolvers

### PR DESCRIPTION
**Pull request by sheerun**

### CODE REVIEW

**Comment by sheerun** [comment]
@stubailo I get:

```
typings/main/globals/apollo-client/index.d.ts(5,17): error TS2694: Namespace '_' has no exported member 'isObject'.
typings/main/globals/apollo-client/index.d.ts(10,17): error TS2694: Namespace '_' has no exported member 'isEqual'.
typings/main/globals/apollo-client/index.d.ts(15,17): error TS2694: Namespace '_' has no exported member 'isArray'.
typings/main/globals/apollo-client/index.d.ts(20,17): error TS2694: Namespace '_' has no exported member 'isNull'.
typings/main/globals/apollo-client/index.d.ts(25,17): error TS2694: Namespace '_' has no exported member 'isString'.
typings/main/globals/apollo-client/index.d.ts(30,17): error TS2694: Namespace '_' has no exported member 'has'.
typings/main/globals/apollo-client/index.d.ts(35,17): error TS2694: Namespace '_' has no exported member 'assign'.
typings/main/globals/apollo-client/index.d.ts(40,17): error TS2694: Namespace '_' has no exported member 'merge'.
typings/main/globals/apollo-client/index.d.ts(45,17): error TS2694: Namespace '_' has no exported member 'includes'.
typings/main/globals/apollo-client/index.d.ts(50,17): error TS2694: Namespace '_' has no exported member 'isNumber'.
typings/main/globals/apollo-client/index.d.ts(55,17): error TS2694: Namespace '_' has no exported member 'isBoolean'.
...
```

**Comment by stubailo** [comment]
Oh gosh, yeah - I forgot this project is still using `typings`. We should try to migrate to types from `npm`. Maybe @kamilkisiela can help, he's a pro at this?

**Comment by sheerun** [comment]
hm?

**Comment by stubailo** [comment]
Sorry, haven't had time to look at this since I'm hard at work preparing for GraphQL summit. Basically, in typescript 2 we're supposed to use types from npm instead of the typings tool we have now.

**Comment by kamilkisiela** [comment]
@stubailo I will take care of this tomorrow

**Comment by kamilkisiela** [comment]
@sheerun You can `git rebase` #13 or just wait for it to be merged :)

**Comment by stubailo** [comment]
Alright let's get this show back on the road!

**Comment by sheerun** [comment]
@stubailo I've rebased on master but I still get the same issue. Could you help to debug?

**Comment by sheerun** [comment]
I've managed to get around it, but I'm not sure you like the solution @stubailo

**Comment by kamilkisiela** [comment]
I'll fix it today. It looks like the `@types/lodash` has changed.

**Comment by sheerun** [comment]
@kamilkisiela https://github.com/lodash/lodash/issues/2795#issuecomment-258879214

**Comment by kamilkisiela** [comment]
@sheerun Why have you updated typescript before?

**Comment by sheerun** [comment]
@kamilkisiela to get async/await feature

**Comment by stubailo** [comment]
Going to close this for now.

**Pull request closed without merging**
