### PR TITLE
Remove a circular dependency

### LINKED ISSUE #27: Circular dependency
Rollup says:
```
ERROR in Circular dependency detected:
../../node_modules/graphql-anywhere/lib/src/utilities.js -> ../../node_modules/graphql-anywhere/lib/src/index.js -> ../../node_modules/graphql-anywhere/lib/src/utilities.js
```

`graphql` function is defined inside `./index.ts`, `./utilities.ts` uses it and also functions from `./utilities.ts` are being imported inside `./index.ts`

#26 should fix it

### PR DESCRIPTION
**Pull request by kamilkisiela**
@DxCx 

Closes #27

### CODE REVIEW

**Comment by helfer** [comment]
@kamilkisiela wow, it's really hard to review when you move a lot of code from one file to another. I imagine the changes you made are actually rather limited. What were they?

**Comment by kamilkisiela** [comment]
@helfer https://www.diffchecker.com/11mTJhq7

I just moved everything related to `graphql` function to `./graphql.ts`

**Comment by kamilkisiela** [comment]
Rebased :+1:

**Comment by helfer** [comment]
@kamilkisiela is this still a blocker for you on something?

**Comment by Urigo** [comment]
@helfer it is for me.   I need to run it on the client through Rollup for the angular.io PR

**Comment by helfer** [comment]
@Urigo how did you finish the angular.io PR without us having merged this??

**Comment by Urigo** [comment]
that's a good question :)
I'm not sure

**Pull request merged**
