### PR TITLE
Update types against GraphQL 0.8.2 and @types/graphql

### PR DESCRIPTION
**Pull request by intellix**
All tests pass. The required @types/graphql is already in DefinitelyTyped

### CODE REVIEW

**Comment by helfer** [comment]
@stubailo @tmeasday should I merge this and publish a new version?

**Comment by tmeasday** [comment]
WFM.

**Comment by stubailo** [comment]
Thanks for finally doing this!

**Comment by stubailo** [comment]
Damn, so this got merged without publishing. I added an unrelated change and now I have to deal with typescript issues.

**Pull request merged**
